FROM node:lts-slim AS client
WORKDIR /app
COPY client/ ./client/
RUN cd client && npm install && npm run build

FROM node:lts-slim AS server
WORKDIR /app
COPY --from=client /app/client/build ./client/build
COPY /package*.json ./
RUN cd server && npm install
COPY server/index.js ./server/

EXPOSE 8080

CMD ["start"]